# Define stages
stages:
  - environment
  - build
  - test
  - deploy


# Check environment
check-environment:
  stage: environment
  image: node:15
  script:
    - node -v
    - npm -v
    - yarn -v


# Install dependencies
build-packages:
  stage: build
  image: node:15
  script:
    - yarn install
    - CI= yarn build
  artifacts:
    paths:
      - build/
      - node_modules/


# Test client
test-client:
  stage: test
  image: node:15
  script:
    - yarn install
    - echo "Testing client dummy code."
    - sleep 10 #yarn test-client
    - echo "Client tested completed."

# Test server
test-server:
  stage: test
  image: node:15
  script:
    - yarn install
    - echo "Testing server dummy code."
    - sleep 10 #yarn test-server
    - echo "Server tested completed."

# Test all
test-all:
  stage: test
  image: node:15
  script:
    - echo "Combined testing server dummy code."
    - sleep 10


# Deploy client to netlify
netlify:
  stage: deploy
  only:
    - main
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
