image: node:9.4.0

# Cache between steps
cache:
  paths:
    - node_modules/
    - .yarn

# Update before starting
before_script:  
  - apt-get update -qq && apt-get install

# Define stages
stages:
  - build
  - test

# Install dependencies and build
build-all:
  stage: build
  before_script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn config set cache-folder .yarn
    - yarn install    
  script:
    - yarn build



# Test client
test-client:
  stage: test
  script:
    - echo "Testing client dummy code."
    - yarn test-client
    - echo "Client tested completed."

# Test server
test-server:
  stage: test
  script:
    - echo "Testing server dummy code."
    - yarn test-server
    - echo "Server tested completed."

# Test all
test-all:
  stage: test
  script:
    - echo "Combined testing server dummy code."
    - sleep 100
    - echo "Server tested completed."