# Define stages
stages:
  - version
  - test
  - build
  - deploy

# Check versions
version-all:
  stage: version
  script:
    - echo "Node:"
    - node -v
    - echo "Npm:"
    - npm -v
    - echo "Yarn:"
    - yarn -v

# Test client
test-client:
  stage: test
  image: node:15
  script:
    - yarn install
    - echo "Testing client dummy code."
    - sleep 10 #yarn test-client
    - echo "Client tested completed."

# Test server
test-server:
  stage: test
  image: node:15
  script:
    - yarn install
    - echo "Testing server dummy code."
    - sleep 10 #yarn test-server
    - echo "Server tested completed."

# Test all
test-all:
  stage: test
  image: node:15
  script:
    - echo "Combined testing server dummy code."
    - sleep 10


# Install dependencies
build-packages:
  stage: build
  image: node:15
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/


# Deploy client to netlify
netlify:
  stage: deploy
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
