#VSC React Client Test

POST https://localhost:8000/api/auth/signup
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "User",
    "email": "test2@email.com",
    "password": "passwd"
}
###
POST https://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "test2@email.com",
    "password": "passwd"
}


###
#Get all Users
GET https://localhost:8000/debug/

###
#Get one user by id
GET https://localhost:8000/api/user/61a0ea4d19c8e8b33eed8ca9

###
#Delete by id
DELETE https://localhost:8000/api/user/61950b7f6eabe064fb5d9922


###
#Update user by id

PATCH https://localhost:8000/api/auth/login/619515019fb45c3950edfb1e
Content-Type: application/json

{
    "name": "ModifiedUser2",
    "interests": ["Not Horror", "Sci-fi"]
    "joinedRooms": ["FirstRoom"]
}


###
POST https://localhost:8000/create
Content-Type: application/json

{
    "title": "Majonéz"
}


#Delete 
###
DELETE https://localhost:8000/delete/5


#Return all books, that have rooms
###
GET https://localhost:8000/book/


###
#Create a book
POST https://localhost:8000/book/create
Content-Type: application/json

{
    "title": "CFrom Zero to One",
    "author": "Author",
    "cover": "./img/zero_one_cover.jfif"
}